In [1]:
import pandas as pd
import numpy as np

Analyze a small, publicly available dataset using Python's NumPy or Pandas libraries.

In [5]:
df = pd.read_csv('Sample - Superstore.csv', encoding='latin1')

1. Explore the data:

Print the first few rows using data.head().
Check the data types of each column using data.info().
Get summary statistics (mean, median, standard deviation, etc.) using data.describe().

In [15]:
#prints the first few rows

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [48]:
#check the data type of each column

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [17]:
#gets summary statistics

df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

2. Calculate basic statistics:

Calculate the mean, median, mode, and standard deviation for each numerical feature.
Calculate the correlation between different features using data.corr().

In [50]:
#selects columns with numeric features

df_num = df.select_dtypes(include='number')

In [13]:
df_num

      Row ID  Postal Code     Sales  Quantity  Discount    Profit
0          1        42420  261.9600         2      0.00   41.9136
1          2        42420  731.9400         3      0.00  219.5820
2          3        90036   14.6200         2      0.00    6.8714
3          4        33311  957.5775         5      0.45 -383.0310
4          5        33311   22.3680         2      0.20    2.5164
...      ...          ...       ...       ...       ...       ...
9989    9990        33180   25.2480         3      0.20    4.1028
9990    9991        92627   91.9600         2      0.00   15.6332
9991    9992        92627  258.5760         2      0.20   19.3932
9992    9993        92627   29.6000         4      0.00   13.3200
9993    9994        92683  243.1600         2      0.00   72.9480

[9994 rows x 6 columns]

In [25]:
df_num = df_num.drop('Row ID', axis=1)

In [26]:
df_num

      Postal Code     Sales  Quantity  Discount    Profit
0           42420  261.9600         2      0.00   41.9136
1           42420  731.9400         3      0.00  219.5820
2           90036   14.6200         2      0.00    6.8714
3           33311  957.5775         5      0.45 -383.0310
4           33311   22.3680         2      0.20    2.5164
...           ...       ...       ...       ...       ...
9989        33180   25.2480         3      0.20    4.1028
9990        92627   91.9600         2      0.00   15.6332
9991        92627  258.5760         2      0.20   19.3932
9992        92627   29.6000         4      0.00   13.3200
9993        92683  243.1600         2      0.00   72.9480

[9994 rows x 5 columns]

In [29]:
num_cols = df_num.columns

In [30]:
list(num_cols)

['Postal Code', 'Sales', 'Quantity', 'Discount', 'Profit']

In [44]:
# Per-feature descriptive statistics

rows = []
for col in num_cols:
    rows.append({
        'Feature':  col,
        'Mean':     round(df[col].mean(), 4),
        'Median':   round(df[col].median(), 4),
        'Mode':     round(df[col].mode()[0], 4),
        'Std Dev':  round(df[col].std(), 4),
    })

In [45]:
rows

[{'Feature': 'Postal Code',
  'Mean': np.float64(55190.3794),
  'Median': 56430.5,
  'Mode': np.int64(10035),
  'Std Dev': 32063.6934},
 {'Feature': 'Sales',
  'Mean': np.float64(229.858),
  'Median': 54.49,
  'Mode': np.float64(12.96),
  'Std Dev': 623.2451},
 {'Feature': 'Quantity',
  'Mean': np.float64(3.7896),
  'Median': 3.0,
  'Mode': np.int64(3),
  'Std Dev': 2.2251},
 {'Feature': 'Discount',
  'Mean': np.float64(0.1562),
  'Median': 0.2,
  'Mode': np.float64(0.0),
  'Std Dev': 0.2065},
 {'Feature': 'Profit',
  'Mean': np.float64(28.6569),
  'Median': 8.6665,
  'Mode': np.float64(0.0),
  'Std Dev': 234.2601}]

In [46]:
#Mean / Median / Mode / Std Dev (per numerical feature)

stats_df = pd.DataFrame(rows).set_index('Feature')

print(stats_df.to_string())

                   Mean      Median      Mode     Std Dev
Feature
Postal Code  55190.3794  56430.5000  10035.00  32063.6934
Sales          229.8580     54.4900     12.96    623.2451
Quantity         3.7896      3.0000      3.00      2.2251
Discount         0.1562      0.2000      0.00      0.2065
Profit          28.6569      8.6665      0.00    234.2601

In [47]:
#data.corr()  — Pearson correlation between numerical features

corr = df[num_cols].corr().round(4)
print(corr.to_string())

             Postal Code   Sales  Quantity  Discount  Profit
Postal Code       1.0000 -0.0239    0.0128    0.0584 -0.0300
Sales            -0.0239  1.0000    0.2008   -0.0282  0.4791
Quantity          0.0128  0.2008    1.0000    0.0086  0.0663
Discount          0.0584 -0.0282    0.0086    1.0000 -0.2195
Profit           -0.0300  0.4791    0.0663   -0.2195  1.0000